export type OpticNames =
    | "Otero Micro Dot"
    | "Kepler Microflex"
    | "Merlin Mini"
    | "PrismaTech Reflex"
    | "Volzhskiy Reflex"
    | "Merlin Reflex"
    | "Redwell Reflex"
    | "Accu-Spot Reflex"
    | "K&S Red Dot"
    | "Otero Red Dot"
    | "OM3 '92 Holo"
    | "Pinpoint Holoscout"
    | "Accu-Spot Ultra Holo"
    | "Jason Armory 2x"
    | "Willis 3x"
    | "Dobrych 4x"
    | "Pinpoint Hybrid"
    | "PrismaPoint Hybrid"
    | "R&K Multizoom"
    | "Otero Thermal 2x"
    | "Remuda Mini Reflex"
    | "Dobrych MF Reflex"
    | "Kepler Red Dot"
    | "PrismaTech 4x"
    | "Blandwell 7x Scope"
    | "Iron Sight"
    | "K&S Thermal Holo"
    | "Kepler Pistol Scope"
    | "Redwell Custom Zoom"
    | "Remuda Dual Zoom"
    | "Remuda Range Finder"
    | "SVD Scope"
    | "Thermal 6x"
    | "VMF Variable Scope";
