name: 'Pull request to development'
on:
  pull_request:
    branches:
      - 'development'

jobs:

  test_pr_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run lint